//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public caja()
        {
            this.cajero = new HashSet<cajero>();
            this.comprobante_fiscal = new HashSet<comprobante_fiscal>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string secuencia { get; set; }
        public int cod_sucursal { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<cajero> cajero { get; set; }
        public virtual ICollection<comprobante_fiscal> comprobante_fiscal { get; set; }
    }
}
