//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajero
    {
        public cajero()
        {
            this.cuadre_caja = new HashSet<cuadre_caja>();
            this.ingresos_caja = new HashSet<ingresos_caja>();
        }
    
        public int codigo { get; set; }
        public Nullable<int> cod_empleado { get; set; }
        public Nullable<int> cod_caja { get; set; }
        public Nullable<byte> activo { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual ICollection<cuadre_caja> cuadre_caja { get; set; }
        public virtual ICollection<ingresos_caja> ingresos_caja { get; set; }
    }
}
