//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria_producto
    {
        public categoria_producto()
        {
            this.oferta_producto_categoria_detalle = new HashSet<oferta_producto_categoria_detalle>();
            this.producto = new HashSet<producto>();
            this.subcategoria_producto = new HashSet<subcategoria_producto>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<oferta_producto_categoria_detalle> oferta_producto_categoria_detalle { get; set; }
        public virtual ICollection<producto> producto { get; set; }
        public virtual ICollection<subcategoria_producto> subcategoria_producto { get; set; }
    }
}
