//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.factura = new HashSet<factura>();
            this.inventario_reparacion = new HashSet<inventario_reparacion>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> limite_credito { get; set; }
        public Nullable<int> cod_categoria { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> fecha_creado { get; set; }
        public Nullable<byte> abrir_credito { get; set; }
        public Nullable<int> cod_sucursal_creado { get; set; }
        public Nullable<byte> cliente_contado { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
    
        public virtual cliente_categoria cliente_categoria { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual ICollection<factura> factura { get; set; }
        public virtual ICollection<inventario_reparacion> inventario_reparacion { get; set; }
    }
}
