//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobros
    {
        public cobros()
        {
            this.cobros_detalles = new HashSet<cobros_detalles>();
        }
    
        public int codigo { get; set; }
        public Nullable<decimal> efectivo { get; set; }
        public Nullable<decimal> devuelta { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string detalle { get; set; }
        public int cod_empleado { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> cod_empleado_anular { get; set; }
        public string motivo_anulado { get; set; }
        public Nullable<byte> cuadrado { get; set; }
    
        public virtual ICollection<cobros_detalles> cobros_detalles { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
