//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobros_detalles
    {
        public int codigo { get; set; }
        public int cod_cobro { get; set; }
        public int cod_factura { get; set; }
        public int cod_metodo_pago { get; set; }
        public Nullable<decimal> monto_pagado { get; set; }
        public Nullable<decimal> monto_descontado { get; set; }
        public Nullable<int> cod_empleado_anular { get; set; }
        public string motivo_anulado { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual cobros cobros { get; set; }
        public virtual metodo_pago metodo_pago { get; set; }
        public virtual factura factura { get; set; }
    }
}
