//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobante_fiscal
    {
        public int codigo { get; set; }
        public int cod_serie { get; set; }
        public int cod_caja { get; set; }
        public int codigo_tipo { get; set; }
        public int desde_numero { get; set; }
        public int hasta_numero { get; set; }
        public int contador { get; set; }
        public int avisar { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual comprobante_serie comprobante_serie { get; set; }
        public virtual tipo_comprobante_fiscal tipo_comprobante_fiscal { get; set; }
    }
}
