//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobante_serie
    {
        public comprobante_serie()
        {
            this.comprobante_fiscal = new HashSet<comprobante_fiscal>();
        }
    
        public int codigo { get; set; }
        public string serie { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<comprobante_fiscal> comprobante_fiscal { get; set; }
    }
}
