//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuadre_caja
    {
        public int codigo { get; set; }
        public int cod_cajero { get; set; }
        public System.DateTime fecha { get; set; }
        public int turno { get; set; }
        public bool activo { get; set; }
        public decimal faltante { get; set; }
        public decimal sobrante { get; set; }
    
        public virtual cajero cajero { get; set; }
    }
}
