//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta_bancaria
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public string numero_cuenta { get; set; }
        public int cod_tipo { get; set; }
        public bool activo { get; set; }
        public Nullable<int> TRIAL_COLUMN6 { get; set; }
        public Nullable<int> TRIAL_COLUMN7 { get; set; }
    }
}
