//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public empresa()
        {
            this.sucursal = new HashSet<sucursal>();
        }
    
        public int codigo { get; set; }
        public string secuencia { get; set; }
        public string division { get; set; }
        public bool activo { get; set; }
        public string rnc { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<sucursal> sucursal { get; set; }
    }
}
