//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada_salida_inventario
    {
        public int codigo { get; set; }
        public string tipo_movimiento { get; set; }
        public int cod_producto { get; set; }
        public int cod_unidad { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cod_almacen { get; set; }
        public Nullable<int> cod_empleado_cambio { get; set; }
        public string motivo { get; set; }
    
        public virtual almacen almacen { get; set; }
        public virtual producto producto { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
