//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public factura()
        {
            this.cobros_detalles = new HashSet<cobros_detalles>();
            this.factura_detalle = new HashSet<factura_detalle>();
        }
    
        public int codigo { get; set; }
        public string num_factura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_limite { get; set; }
        public Nullable<int> codigo_empleado { get; set; }
        public Nullable<int> codigo_cliente { get; set; }
        public string rnc { get; set; }
        public string ncf { get; set; }
        public string codigo_tipo_factura { get; set; }
        public Nullable<int> cod_sucursal { get; set; }
        public Nullable<sbyte> activo { get; set; }
        public Nullable<sbyte> pagada { get; set; }
        public Nullable<int> cod_empleado_anular { get; set; }
        public Nullable<decimal> devuelta { get; set; }
        public Nullable<decimal> itebis { get; set; }
        public Nullable<decimal> efectivo { get; set; }
        public string motivo_anulada { get; set; }
        public Nullable<decimal> monto_propina { get; set; }
        public Nullable<int> cod_vendedor { get; set; }
        public Nullable<int> despachado { get; set; }
        public Nullable<int> autorizar_pedido { get; set; }
        public Nullable<int> cuadrado { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public string detalles { get; set; }
        public Nullable<int> codigo_comprobante { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<cobros_detalles> cobros_detalles { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual tipo_comprobante_fiscal tipo_comprobante_fiscal { get; set; }
        public virtual ICollection<factura_detalle> factura_detalle { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
