//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_detalle
    {
        public int cod_factura { get; set; }
        public int cod_producto { get; set; }
        public int cod_unidad { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal monto { get; set; }
        public decimal itebis { get; set; }
        public decimal descuento { get; set; }
        public Nullable<byte> estado { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
