//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int codigo { get; set; }
        public int codigo_producto { get; set; }
        public int codigo_unidad { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<System.DateTime> fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
