//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class itebis
    {
        public itebis()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public int porciento { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
    }
}
