//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesas
    {
        public mesas()
        {
            this.mesas_detalles = new HashSet<mesas_detalles>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<sbyte> activo { get; set; }
        public Nullable<int> cod_sucursal { get; set; }
    
        public virtual ICollection<mesas_detalles> mesas_detalles { get; set; }
    }
}
