//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class metodo_pago
    {
        public metodo_pago()
        {
            this.cobros_detalles = new HashSet<cobros_detalles>();
            this.pagos_detalles = new HashSet<pagos_detalles>();
        }
    
        public int codigo { get; set; }
        public string metodo { get; set; }
        public string descripcion { get; set; }
        public Nullable<byte> activo { get; set; }
    
        public virtual ICollection<cobros_detalles> cobros_detalles { get; set; }
        public virtual ICollection<pagos_detalles> pagos_detalles { get; set; }
    }
}
