//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulos_vs_ventanas
    {
        public int id_modulo { get; set; }
        public Nullable<int> id_ventana { get; set; }
    
        public virtual sistema_modulo sistema_modulo { get; set; }
        public virtual sistema_ventanas sistema_ventanas { get; set; }
    }
}
