//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneda
    {
        public moneda()
        {
            this.moneda_historial = new HashSet<moneda_historial>();
            this.sistema = new HashSet<sistema>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public decimal tasa_actual { get; set; }
        public Nullable<bool> activo { get; set; }
        public string monedacol { get; set; }
    
        public virtual ICollection<moneda_historial> moneda_historial { get; set; }
        public virtual ICollection<sistema> sistema { get; set; }
    }
}
