//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneda_historial
    {
        public int codigo { get; set; }
        public int cod_moneda { get; set; }
        public decimal tasa { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual moneda moneda { get; set; }
    }
}
