//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomina_detalle
    {
        public int cod_nomina { get; set; }
        public int cod_empleado { get; set; }
        public int cod_concepto { get; set; }
        public decimal monto_sueldo { get; set; }
        public Nullable<int> cod_empleado_modifico { get; set; }
        public Nullable<sbyte> activo { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual nomina nomina { get; set; }
        public virtual nomina_conceptos nomina_conceptos { get; set; }
    }
}
