//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta_producto_categoria_detalle
    {
        public int cod_oferta { get; set; }
        public int cod_categoria { get; set; }
        public sbyte activo { get; set; }
    
        public virtual categoria_producto categoria_producto { get; set; }
    }
}
