//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_codigobarra
    {
        public int cod_producto { get; set; }
        public int cod_unidad { get; set; }
        public string codigo_barra { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
