//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_oferta_historial
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<System.DateTime> fecha_inicial { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_actualizada { get; set; }
        public Nullable<int> cod_empleado_actualiza { get; set; }
        public int cod_sucursal { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
