//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_detalle
    {
        public producto_detalle()
        {
            this.mesas_detalles = new HashSet<mesas_detalles>();
            this.producto_vs_detalle = new HashSet<producto_vs_detalle>();
        }
    
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<byte> activo { get; set; }
    
        public virtual ICollection<mesas_detalles> mesas_detalles { get; set; }
        public virtual ICollection<producto_vs_detalle> producto_vs_detalle { get; set; }
    }
}
