//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public region()
        {
            this.provincia = new HashSet<provincia>();
        }
    
        public int codigo { get; set; }
        public int cod_pais { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        public virtual pais pais { get; set; }
        public virtual ICollection<provincia> provincia { get; set; }
    }
}
