//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistema_ventanas
    {
        public sistema_ventanas()
        {
            this.modulos_vs_ventanas = new HashSet<modulos_vs_ventanas>();
        }
    
        public int codigo { get; set; }
        public string nombre_ventana { get; set; }
        public string nombre_logico { get; set; }
        public string imagen { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<modulos_vs_ventanas> modulos_vs_ventanas { get; set; }
    }
}
