//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public sucursal()
        {
            this.almacen = new HashSet<almacen>();
            this.cliente = new HashSet<cliente>();
            this.compra = new HashSet<compra>();
            this.empleado = new HashSet<empleado>();
            this.factura = new HashSet<factura>();
            this.nomina = new HashSet<nomina>();
            this.empleado_historial_datos = new HashSet<empleado_historial_datos>();
            this.producto_oferta_historial = new HashSet<producto_oferta_historial>();
            this.suplidor = new HashSet<suplidor>();
        }
    
        public int codigo { get; set; }
        public int codigo_empresa { get; set; }
        public string secuencia { get; set; }
        public bool activo { get; set; }
        public string direccion { get; set; }
    
        public virtual ICollection<almacen> almacen { get; set; }
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<compra> compra { get; set; }
        public virtual ICollection<empleado> empleado { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<factura> factura { get; set; }
        public virtual ICollection<nomina> nomina { get; set; }
        public virtual ICollection<empleado_historial_datos> empleado_historial_datos { get; set; }
        public virtual ICollection<producto_oferta_historial> producto_oferta_historial { get; set; }
        public virtual ICollection<suplidor> suplidor { get; set; }
    }
}
