//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplidor
    {
        public suplidor()
        {
            this.compra = new HashSet<compra>();
        }
    
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string rnc { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int cod_sucursal_creado { get; set; }
        public Nullable<decimal> limite_credito { get; set; }
        public bool activo { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public Nullable<long> tipo_gasto { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual ICollection<compra> compra { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual tipo_gasto tipo_gasto1 { get; set; }
    }
}
