//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_comprobante_fiscal
    {
        public tipo_comprobante_fiscal()
        {
            this.comprobante_fiscal = new HashSet<comprobante_fiscal>();
            this.factura = new HashSet<factura>();
        }
    
        public int codigo { get; set; }
        public string secuencia { get; set; }
        public string nombre { get; set; }
        public sbyte activo { get; set; }
    
        public virtual ICollection<comprobante_fiscal> comprobante_fiscal { get; set; }
        public virtual ICollection<factura> factura { get; set; }
    }
}
