//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrisContabilidadModelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferencia_inventario
    {
        public int codigo { get; set; }
        public string tipo_movimiento { get; set; }
        public int cod_producto { get; set; }
        public int cod_unidad { get; set; }
        public decimal cantidad { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> codigo_sucursal_origen { get; set; }
        public Nullable<int> codigo_almacen_origen { get; set; }
        public Nullable<int> codigo_sucursal_destino { get; set; }
        public Nullable<int> codigo_almacen_destino { get; set; }
        public Nullable<int> codigo_empleado { get; set; }
    }
}
